[package]
name = "leftwm"
version = "0.3.0"
authors = ["Lex Childs <lexchilds@gmail.com>"]
categories = ["window manager"]
edition = "2021"
keywords = ["wm", "window", "manager"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/leftwm/leftwm"
description = "A window manager for Adventurers"

[dependencies]
anyhow = "1.0.48"
clap = { version = "3.2.12", features = ["cargo"] }
const_format = "0.2.26"
once_cell = "1.13.0"
dirs-next = "2.0.0"
futures = "0.3.21"
git-version = "0.3.4"
leftwm-core = { path = "../leftwm-core", version = '0.3.0' }
liquid = "0.24.0"
log = "0.4.8"
mio = "0.8.0"
nix = "0.23.0"
serde = { version = "1.0.104", features = ["derive", "rc"] }
serde_json = "1.0.44"
shellexpand = "2.1"
signal-hook = "0.3.4"
thiserror = "1.0.30"
time_leftwm = { package = "time", version = "0.3.7", features = [
  "macros",
  "formatting",
  "local-offset",
] }
tokio = { version = "1.2.0", features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "time",
] }
toml = "0.5.5"
x11-dl = "2.18.4"
xdg = "2.2.0"

# logging
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
tracing-journald = {version = "0.3.0", optional = true}
tracing-appender = {version = "0.2.2", optional = true}

[dev-dependencies]
tempfile = "3.2.0"

[features]
default = ["journald-log", "file-log"]

# logging features
journald-log = ["tracing-journald"]
file-log = ["tracing-appender"]

# Sleep on restart
slow-dm-fix = []
